"""create photo model

Revision ID: 9d7c16e14728
Revises: 
Create Date: 2024-06-16 18:04:31.920747

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "9d7c16e14728"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "photos",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column(
            "image_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_photos_description"), "photos", ["description"], unique=False
    )
    op.create_index(op.f("ix_photos_id"), "photos", ["id"], unique=False)
    op.create_index(
        op.f("ix_photos_image_url"), "photos", ["image_url"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_photos_image_url"), table_name="photos")
    op.drop_index(op.f("ix_photos_id"), table_name="photos")
    op.drop_index(op.f("ix_photos_description"), table_name="photos")
    op.drop_table("photos")
    # ### end Alembic commands ###
